### ISSUE TITLE
Can't delete a user group

### ISSUE THREAD

**Issue by rminchev1** [rndsolutions/hawkcd#136] opened 2016-08-11 10:47 UTC

**Comment by monitobeko** [comment] 2016-08-19 12:32
@rminchev1 I'm unable to reproduce the issue. Please provide additional details. Also, please note deleting User Groups while Users are assigned to them is not allowed.

**Comment by rminchev1** [comment] 2016-08-19 12:39
Got it, we may close it then.

**Closed** 2016-08-19 12:41 UTC
Labels: bug
